const moment = require("moment");

module.exports = Object.freeze({
  CALENDAR_INITIAL_EVENTS: [
    {
      title: "Product call",
      theme: "GREEN",
      startTime: moment().add(-12, "d").startOf("day"),
      endTime: moment().add(-12, "d").endOf("day"),
    },
    {
      title: "Meeting with tech team",
      theme: "PINK",
      startTime: moment().add(-8, "d").startOf("day"),
      endTime: moment().add(-8, "d").endOf("day"),
    },
    {
      title: "Meeting with Cristina",
      theme: "PURPLE",
      startTime: moment().add(-2, "d").startOf("day"),
      endTime: moment().add(-2, "d").endOf("day"),
    },
    {
      title: "Meeting with Alex",
      theme: "BLUE",
      startTime: moment().startOf("day"),
      endTime: moment().endOf("day"),
    },
    {
      title: "Product Call",
      theme: "GREEN",
      startTime: moment().startOf("day"),
      endTime: moment().endOf("day"),
    },
    {
      title: "Client Meeting",
      theme: "PURPLE",
      startTime: moment().startOf("day"),
      endTime: moment().endOf("day"),
    },
    {
      title: "Client Meeting",
      theme: "ORANGE",
      startTime: moment().add(3, "d").startOf("day"),
      endTime: moment().add(3, "d").endOf("day"),
    },
    {
      title: "Product meeting",
      theme: "PINK",
      startTime: moment().add(5, "d").startOf("day"),
      endTime: moment().add(5, "d").endOf("day"),
    },
    {
      title: "Sales Meeting",
      theme: "GREEN",
      startTime: moment().add(8, "d").startOf("day"),
      endTime: moment().add(8, "d").endOf("day"),
    },
    {
      title: "Product Meeting",
      theme: "ORANGE",
      startTime: moment().add(8, "d").startOf("day"),
      endTime: moment().add(8, "d").endOf("day"),
    },
    {
      title: "Marketing Meeting",
      theme: "PINK",
      startTime: moment().add(8, "d").startOf("day"),
      endTime: moment().add(8, "d").endOf("day"),
    },
    {
      title: "Client Meeting",
      theme: "GREEN",
      startTime: moment().add(8, "d").startOf("day"),
      endTime: moment().add(8, "d").endOf("day"),
    },
    {
      title: "Sales meeting",
      theme: "BLUE",
      startTime: moment().add(12, "d").startOf("day"),
      endTime: moment().add(12, "d").endOf("day"),
    },
    {
      title: "Client meeting",
      theme: "PURPLE",
      startTime: moment().add(16, "d").startOf("day"),
      endTime: moment().add(16, "d").endOf("day"),
    },
  ],
  RECENT_TRANSACTIONS: [
    {
      name: "Alex",
      avatar: "https://reqres.in/img/faces/1-image.jpg",
      email: "alex@trip.com",
      location: "Eiffel Tower, Paris",
      amount: 100,
      date: moment().endOf("day"),
    },
    {
      name: "Ereena",
      avatar: "https://reqres.in/img/faces/2-image.jpg",
      email: "ereena@trip.com",
      location: "Tower of London, London",
      amount: 190,
      date: moment().add(-1, "d").endOf("day"),
    },
    {
      name: "John",
      avatar: "https://reqres.in/img/faces/3-image.jpg",
      email: "jhon@trip.com",
      location: "Niagara Falls, Canada",
      amount: 112,
      date: moment().add(-1, "d").endOf("day"),
    },
    {
      name: "Matrix",
      avatar: "https://reqres.in/img/faces/4-image.jpg",
      email: "matrix@trip.com",
      location: "Machu Picchu, Peru",
      amount: 111,
      date: moment().add(-1, "d").endOf("day"),
    },
    {
      name: "Virat",
      avatar: "https://reqres.in/img/faces/5-image.jpg",
      email: "virat@trip.com",
      location: "Big Ben, London",
      amount: 190,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "Miya",
      avatar: "https://reqres.in/img/faces/6-image.jpg",
      email: "miya@trip.com",
      location: "Louvre Museum, Paris",
      amount: 230,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "Virat",
      avatar: "https://reqres.in/img/faces/3-image.jpg",
      email: "virat@trip.com",
      location: "CN Tower, Canada",
      amount: 331,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "Matrix",
      avatar: "https://reqres.in/img/faces/1-image.jpg",
      email: "matrix@trip.com",
      location: "Buckingham Palace, London",
      amount: 581,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "Ereena",
      avatar: "https://reqres.in/img/faces/3-image.jpg",
      email: "ereena@trip.com",
      location: "Mount Fuji, Tokyo",
      amount: 151,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "John",
      avatar: "https://reqres.in/img/faces/2-image.jpg",
      email: "jhon@trip.com",
      location: "Notre-Dame Cathedral, Paris",
      amount: 91,
      date: moment().add(-2, "d").endOf("day"),
    },
    {
      name: "Virat",
      avatar: "https://reqres.in/img/faces/3-image.jpg",
      email: "virat@trip.com",
      location: "Banff National Park, Canada",
      amount: 161,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "Matrix",
      avatar: "https://reqres.in/img/faces/4-image.jpg",
      email: "matrix@trip.com",
      location: "Statue of Liberty, US",
      amount: 121,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "Ereena",
      avatar: "https://reqres.in/img/faces/6-image.jpg",
      email: "jhon@trip.com",
      location: "Shibuya Crossing, Tokyo",
      amount: 713,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "John",
      avatar: "https://reqres.in/img/faces/2-image.jpg",
      email: "ereena@trip.com",
      location: "British Museum, London",
      amount: 217,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "Virat",
      avatar: "https://reqres.in/img/faces/3-image.jpg",
      email: "virat@trip.com",
      location: "Champs-Élysées, Paris",
      amount: 117,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "Miya",
      avatar: "https://reqres.in/img/faces/7-image.jpg",
      email: "jhon@trip.com",
      location: "Whistler Mountain, Canada",
      amount: 612,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "Matrix",
      avatar: "https://reqres.in/img/faces/3-image.jpg",
      email: "matrix@trip.com",
      location: "Trafalgar Square, London",
      amount: 631,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "Virat",
      avatar: "https://reqres.in/img/faces/2-image.jpg",
      email: "ereena@trip.com",
      location: "Sensō-ji Temple, Tokyo",
      amount: 151,
      date: moment().add(-3, "d").endOf("day"),
    },
    {
      name: "Ereena",
      avatar: "https://reqres.in/img/faces/3-image.jpg",
      email: "virat@trip.com",
      location: "Arc de Triomphe, Paris",
      amount: 617,
      date: moment().add(-3, "d").endOf("day"),
    },
  ],
});
